"""add_public_url_to_reports

Revision ID: 9d20d172cf80
Revises: 8171f449f5a5
Create Date: 2026-04-28 23:23:37.160548

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '9d20d172cf80'
down_revision: str | None = '8171f449f5a5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('public_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'public_url')
    # ### end Alembic commands ###
